apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict
spec:
  replicas: 2
  selector:
    matchLabels:
      name: predict
  template:
    metadata:
      labels:
        name: predict
    spec:
      containers:
        - name: predict
          image: rg.fr-par.scw.cloud/namespace-ota/docker-predict:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: rest
---
# service
apiVersion: v1
kind: Service
metadata:
  name: predict-service
spec:
  selector:
    name: predict
  ports:
    - port: 80
      targetPort: rest
  type: LoadBalancer