apiVersion: v1
kind: PersistentVolume
metadata:
  name: ota-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce  # Use appropriate access mode for your use case
  persistentVolumeReclaimPolicy: Retain  # Adjust as needed
  storageClassName: standard  # Storage class name
  hostPath:
    path: /app/data  # Path on the host machine, or use other storage options

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ota-pvc2
spec:
  accessModes:
    - ReadWriteOnce  # Use the same access mode as in your PV
  resources:
    requests:
      storage: 1Gi  # Requested storage size, should match the PV size
  storageClassName: standard  # Storage class name, should match PV's storage clas